# Generated by Django 4.2.16 on 2024-11-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
