# Generated by Django 4.2.16 on 2024-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_site',
            field=models.URLField(default='https://default.com', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.URLField(default='https://default.com', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(default='placeholder', verbose_name='html'),
        ),
    ]
