# Generated by Django 4.2.16 on 2024-12-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_deployed_site_project_repository_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
