# Generated by Django 4.2.16 on 2024-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_deployed_site_alter_project_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deployed_site',
            field=models.URLField(default='https://default.com', verbose_name='Deployed URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(default='https://default.com', verbose_name='GitHub URL'),
        ),
    ]
